# Generated by Django 5.2 on 2025-10-16 19:31

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('image_of_university', models.ImageField(null=True, upload_to='university_images/')),
                ('content', tinymce.models.HTMLField(default='')),
                ('overview', models.CharField(max_length=300, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
