# Generated by Django 5.2 on 2025-10-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments', '0002_remove_post_image_of_university_post_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
